version: "4.1"

services:
    # app:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     ports:
    #         - 3000:3000
    #     depends_on:
    #         - db

    db:
        image: postgres:12.7-alpine
        restart: always
        environment:
            POSTGRES_DB: contele
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 12345
        ports:
            - 5432:5432
